services:
  app:
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    build: ./docker/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data      

volumes:
  postgres-data: